
export const leftTopTable = {
    data1: [{
        month: '2023-08',
        enterpriseName: '金川集团',
        productName: '镍',
        productuUnit: '万吨',
        productionThisMonth: '1.35',
        lastMonth: '1.35',
        yearTotal: '10.72',
        ConteProduction: '10.09',
        YOY: "6.24"
    },
    {
        month: '2023-08',
        enterpriseName: '金川集团',
        productName: '铜',
        productuUnit: '万吨',
        productionThisMonth: '10.4',
        lastMonth: '9.47',
        yearTotal: '82.36',
        ConteProduction: '72.23',
        YOY: "14.02"
    },
    {
        month: '2023-08',
        enterpriseName: '酒钢集团',
        productName: '钢材',
        productuUnit: '万吨',
        productionThisMonth: '65.59',
        lastMonth: '71.89',
        yearTotal: '632.26',
        ConteProduction: '674',
        YOY: "-6.19"
    },
    {
        month: '2023-08',
        enterpriseName: '酒钢集团',
        productName: '铝',
        productuUnit: '万吨',
        productionThisMonth: '14.37',
        lastMonth: '14.38',
        yearTotal: '113.19',
        ConteProduction: '111',
        YOY: "1.97"
    },
    {
        month: '2023-08',
        enterpriseName: '白银集团',
        productName: '铜',
        productuUnit: '万吨',
        productionThisMonth: '2.88',
        lastMonth: '2.6',
        yearTotal: '19.32',
        ConteProduction: '16.87',
        YOY: "14.52"
    },
    {
        month: '2023-08',
        enterpriseName: '白银集团',
        productName: '铅',
        productuUnit: '万吨',
        productionThisMonth: '0.21',
        lastMonth: '0.21',
        yearTotal: '1.53',
        ConteProduction: '1.27',
        YOY: "20.47"
    },
    {
        month: '2023-08',
        enterpriseName: '白银集团',
        productName: '锌',
        productuUnit: '万吨',
        productionThisMonth: '3.18',
        lastMonth: '2.26',
        yearTotal: '25.95',
        ConteProduction: '24.46',
        YOY: "6.09"
    },
    {
        month: '2023-06',
        enterpriseName: '金川集团',
        productName: '镍',
        productuUnit: '万吨',
        productionThisMonth: '1.53',
        lastMonth: '1.38',
        yearTotal: '8.02',
        ConteProduction: '7.48',
        YOY: "7.22"
    },
    {
        month: '2023-06',
        enterpriseName: '金川集团',
        productName: '铜',
        productuUnit: '万吨',
        productionThisMonth: '11.73',
        lastMonth: '11.11',
        yearTotal: '62.49',
        ConteProduction: '55.48',
        YOY: "12.64"
    },
    {
        month: '2023-06',
        enterpriseName: '酒钢集团',
        productName: '钢材',
        productuUnit: '万吨',
        productionThisMonth: '65.32',
        lastMonth: '75.57',
        yearTotal: '494.78',
        ConteProduction: '534',
        YOY: "-7.34"
    },
    {
        month: '2023-06',
        enterpriseName: '酒钢集团',
        productName: '铝',
        productuUnit: '万吨',
        productionThisMonth: '13.9',
        lastMonth: '14.42',
        yearTotal: '84.44',
        ConteProduction: '83',
        YOY: "1.73"
    },
    {
        month: '2023-06',
        enterpriseName: '白银集团',
        productName: '铜',
        productuUnit: '万吨',
        productionThisMonth: '4.06',
        lastMonth: '1.72',
        yearTotal: '13.84',
        ConteProduction: '10.09',
        YOY: "37.17"
    },
    {
        month: '2023-06',
        enterpriseName: '白银集团',
        productName: '铅',
        productuUnit: '万吨',
        productionThisMonth: '0.37',
        lastMonth: '0.2',
        yearTotal: '1.11',
        ConteProduction: '0.75',
        YOY: "48"
    },
    {
        month: '2023-06',
        enterpriseName: '白银集团',
        productName: '锌',
        productuUnit: '万吨',
        productionThisMonth: '5.9',
        lastMonth: '3.47',
        yearTotal: '20.51',
        ConteProduction: '17.76',
        YOY: "15.48"
    },
    {
        month: '2023-05',
        enterpriseName: '金川集团',
        productName: '镍',
        productuUnit: '万吨',
        productionThisMonth: '1.38',
        lastMonth: '1.28',
        yearTotal: '6.49',
        ConteProduction: '5.96',
        YOY: "8.89"
    },
    {
        month: '2023-05',
        enterpriseName: '金川集团',
        productName: '铜',
        productuUnit: '万吨',
        productionThisMonth: '11.11',
        lastMonth: '11.01',
        yearTotal: '50.76',
        ConteProduction: '45.65',
        YOY: "11.19"
    },
    {
        month: '2023-05',
        enterpriseName: '酒钢集团',
        productName: '钢材',
        productuUnit: '万吨',
        productionThisMonth: '75.57',
        lastMonth: '83.63',
        yearTotal: '429.46',
        ConteProduction: '444.99',
        YOY: "-3.49"
    },
    {
        month: '2023-05',
        enterpriseName: '酒钢集团',
        productName: '铝',
        productuUnit: '万吨',
        productionThisMonth: '14.42',
        lastMonth: '13.86',
        yearTotal: '70.54',
        ConteProduction: '69',
        YOY: "2.23"
    },
    {
        month: '2023-05',
        enterpriseName: '白银集团',
        productName: '铜',
        productuUnit: '万吨',
        productionThisMonth: '1.66',
        lastMonth: '1.72',
        yearTotal: '11.44',
        ConteProduction: '10.09',
        YOY: "13.38"
    },
    {
        month: '2023-05',
        enterpriseName: '白银集团',
        productName: '铅',
        productuUnit: '万吨',
        productionThisMonth: '0.16',
        lastMonth: '0.2',
        yearTotal: '0.9',
        ConteProduction: '0.75',
        YOY: "20"
    },
    {
        month: '2023-05',
        enterpriseName: '白银集团',
        productName: '锌',
        productuUnit: '万吨',
        productionThisMonth: '3.27',
        lastMonth: '3.5',
        yearTotal: '17.07',
        ConteProduction: '17.25',
        YOY: "-0.76"
    },
    {
        month: '2023-04',
        enterpriseName: '金川集团',
        productName: '镍',
        productuUnit: '万吨',
        productionThisMonth: '1.28',
        lastMonth: '1.36',
        yearTotal: '5.1',
        ConteProduction: '4.65',
        YOY: "9.68"
    },
    {
        month: '2023-04',
        enterpriseName: '金川集团',
        productName: '铜',
        productuUnit: '万吨',
        productionThisMonth: '11.01',
        lastMonth: '9.68',
        yearTotal: '39.64',
        ConteProduction: '35.93',
        YOY: "10.33"
    },
    {
        month: '2023-04',
        enterpriseName: '酒钢集团',
        productName: '钢材',
        productuUnit: '万吨',
        productionThisMonth: '83.63',
        lastMonth: '96.02',
        yearTotal: '352.89',
        ConteProduction: '358.99',
        YOY: "-1.70"
    },
    {
        month: '2023-04',
        enterpriseName: '酒钢集团',
        productName: '铝',
        productuUnit: '万吨',
        productionThisMonth: '13.86',
        lastMonth: '14.35',
        yearTotal: '56.12',
        ConteProduction: '55',
        YOY: "2.04"
    },
    {
        month: '2023-04',
        enterpriseName: '白银集团',
        productName: '铜',
        productuUnit: '万吨',
        productionThisMonth: '1.72',
        lastMonth: '2.86',
        yearTotal: '9.78',
        ConteProduction: '7.64',
        YOY: "28.01"
    },
    {
        month: '2023-04',
        enterpriseName: '白银集团',
        productName: '铅',
        productuUnit: '万吨',
        productionThisMonth: '0.2',
        lastMonth: '0.17',
        yearTotal: '0.74',
        ConteProduction: '0.75',
        YOY: "-1.33"
    },
    {
        month: '2023-04',
        enterpriseName: '白银集团',
        productName: '锌',
        productuUnit: '万吨',
        productionThisMonth: '3.5',
        lastMonth: '3.18',
        yearTotal: '13.8',
        ConteProduction: '14.11',
        YOY: "-2.20"
    },
    {
        month: '2023-03',
        enterpriseName: '金川集团',
        productName: '镍',
        productuUnit: '万吨',
        productionThisMonth: '1.36',
        lastMonth: '1.37',
        yearTotal: '3.82',
        ConteProduction: '3.54',
        YOY: "7.91"
    },
    {
        month: '2023-03',
        enterpriseName: '金川集团',
        productName: '铜',
        productuUnit: '万吨',
        productionThisMonth: '9.68',
        lastMonth: '10.35',
        yearTotal: '28.63',
        ConteProduction: '26.18',
        YOY: "9.36"
    },
    {
        month: '2023-03',
        enterpriseName: '酒钢集团',
        productName: '钢材',
        productuUnit: '万吨',
        productionThisMonth: '96.02',
        lastMonth: '86.24',
        yearTotal: '269.26',
        ConteProduction: '268',
        YOY: "0.47"
    },
    {
        month: '2023-03',
        enterpriseName: '酒钢集团',
        productName: '铝',
        productuUnit: '万吨',
        productionThisMonth: '14.35',
        lastMonth: '12.91',
        yearTotal: '42.26',
        ConteProduction: '41',
        YOY: "3.07"
    },
    {
        month: '2023-03',
        enterpriseName: '白银集团',
        productName: '铜',
        productuUnit: '万吨',
        productionThisMonth: '2.86',
        lastMonth: '2.55',
        yearTotal: '8.06',
        ConteProduction: '5.72',
        YOY: "40.91"
    },
    {
        month: '2023-03',
        enterpriseName: '白银集团',
        productName: '铅',
        productuUnit: '万吨',
        productionThisMonth: '0.17',
        lastMonth: '0.19',
        yearTotal: '0.54',
        ConteProduction: '0.59',
        YOY: "-8.47"
    },
    {
        month: '2023-03',
        enterpriseName: '白银集团',
        productName: '锌',
        productuUnit: '万吨',
        productionThisMonth: '3.18',
        lastMonth: '3.54',
        yearTotal: '10.31',
        ConteProduction: '11.64',
        YOY: "-11.43"
    },
    {
        month: '2023-02',
        enterpriseName: '金川集团',
        productName: '镍',
        productuUnit: '万吨',
        productionThisMonth: '1.37',
        lastMonth: '1.09',
        yearTotal: '2.46',
        ConteProduction: '2.34',
        YOY: "5.13"
    },
    {
        month: '2023-02',
        enterpriseName: '金川集团',
        productName: '铜',
        productuUnit: '万吨',
        productionThisMonth: '10.35',
        lastMonth: '8.61',
        yearTotal: '18.95',
        ConteProduction: '17.21',
        YOY: "10.11"
    },
    {
        month: '2023-02',
        enterpriseName: '酒钢集团',
        productName: '钢材',
        productuUnit: '万吨',
        productionThisMonth: '86.24',
        lastMonth: '87',
        yearTotal: '173.24',
        ConteProduction: '175.01',
        YOY: "-1.01"
    },
    {
        month: '2023-02',
        enterpriseName: '酒钢集团',
        productName: '铝',
        productuUnit: '万吨',
        productionThisMonth: '12.91',
        lastMonth: '15',
        yearTotal: '27.91',
        ConteProduction: '27',
        YOY: "3.37"
    },
    {
        month: '2023-02',
        enterpriseName: '白银集团',
        productName: '铜',
        productuUnit: '万吨',
        productionThisMonth: '2.55',
        lastMonth: '2.65',
        yearTotal: '5.2',
        ConteProduction: '3.77',
        YOY: "37.93"
    },
    {
        month: '2023-02',
        enterpriseName: '白银集团',
        productName: '铅',
        productuUnit: '万吨',
        productionThisMonth: '0.19',
        lastMonth: '0.19',
        yearTotal: '0.37',
        ConteProduction: '0.37',
        YOY: "0"
    },
    {
        month: '2023-02',
        enterpriseName: '白银集团',
        productName: '锌',
        productuUnit: '万吨',
        productionThisMonth: '3.54',
        lastMonth: '3.55',
        yearTotal: '7.09',
        ConteProduction: '7.53',
        YOY: "-5.84"
    },
    {
        month: '2023-01',
        enterpriseName: '金川集团',
        productName: '镍',
        productuUnit: '万吨',
        productionThisMonth: '1.09',
        lastMonth: '1.05',
        yearTotal: '1.09',
        ConteProduction: '1.09',
        YOY: "0"
    },
    {
        month: '2023-01',
        enterpriseName: '金川集团',
        productName: '铜',
        productuUnit: '万吨',
        productionThisMonth: '8.61',
        lastMonth: '9.89',
        yearTotal: '8.61',
        ConteProduction: '7.91',
        YOY: "8.85"
    },
    {
        month: '2023-01',
        enterpriseName: '酒钢集团',
        productName: '钢材',
        productuUnit: '万吨',
        productionThisMonth: '87',
        lastMonth: '107.81',
        yearTotal: '87',
        ConteProduction: '89',
        YOY: "-2.25"
    },
    {
        month: '2023-01',
        enterpriseName: '酒钢集团',
        productName: '铝',
        productuUnit: '万吨',
        productionThisMonth: '15',
        lastMonth: '15',
        yearTotal: '15',
        ConteProduction: '14',
        YOY: "7.14"
    },
    {
        month: '2023-01',
        enterpriseName: '白银集团',
        productName: '铜',
        productuUnit: '万吨',
        productionThisMonth: '2.65',
        lastMonth: '7.36',
        yearTotal: '2.65',
        ConteProduction: '1.7',
        YOY: "55.88"
    },
    {
        month: '2023-01',
        enterpriseName: '白银集团',
        productName: '铅',
        productuUnit: '万吨',
        productionThisMonth: '0.19',
        lastMonth: '0.25',
        yearTotal: '0.19',
        ConteProduction: '0.17',
        YOY: "11.76"
    },
    {
        month: '2023-01',
        enterpriseName: '白银集团',
        productName: '锌',
        productuUnit: '万吨',
        productionThisMonth: '3.55',
        lastMonth: '4.59',
        yearTotal: '3.55',
        ConteProduction: '3.6',
        YOY: "-1.39"
    },
    ],
    data2: [
        {
            month: '2023-08',
            enterpriseName: '甘肃能化靖煤公司',
            productName: '原煤',
            productuUnit: '万吨',
            productionThisMonth: '75.61',
            lastMonth: '76.6',
            yearTotal: '618.38',
            ConteProduction: '572.63',
            YOY: "7.99"
        },
        {
            month: '2023-08',
            enterpriseName: '甘肃能化窑煤公司',
            productName: '原煤',
            productuUnit: '万吨',
            productionThisMonth: '88.16',
            lastMonth: '52.02',
            yearTotal: '631.51',
            ConteProduction: '366.6',
            YOY: "72.26"
        },
        {
            month: '2023-06',
            enterpriseName: '甘肃能化靖煤公司',
            productName: '原煤',
            productuUnit: '万吨',
            productionThisMonth: '77.62',
            lastMonth: '74.04',
            yearTotal: '466.17',
            ConteProduction: '436.3',
            YOY: "6.85"
        },
        {
            month: '2023-06',
            enterpriseName: '甘肃能化窑煤公司',
            productName: '原煤',
            productuUnit: '万吨',
            productionThisMonth: '79.76',
            lastMonth: '81.05',
            yearTotal: '552.32',
            ConteProduction: '291.37',
            YOY: "89.56"
        },
        {
            month: '2023-05',
            enterpriseName: '甘肃能化靖煤公司',
            productName: '原煤',
            productuUnit: '万吨',
            productionThisMonth: '74.04',
            lastMonth: '75.92',
            yearTotal: '388.55',
            ConteProduction: '364.15',
            YOY: "6.70"
        },
        {
            month: '2023-05',
            enterpriseName: '甘肃能化窑煤公司',
            productName: '原煤',
            productuUnit: '万吨',
            productionThisMonth: '81.05',
            lastMonth: '76.72',
            yearTotal: '411.56',
            ConteProduction: '294.48',
            YOY: "39.76"
        },
        {
            month: '2023-04',
            enterpriseName: '甘肃能化靖煤公司',
            productName: '原煤',
            productuUnit: '万吨',
            productionThisMonth: '75.92',
            lastMonth: '83.03',
            yearTotal: '314.5',
            ConteProduction: '292.59',
            YOY: "7.49"
        },
        {
            month: '2023-04',
            enterpriseName: '甘肃能化窑煤公司',
            productName: '原煤',
            productuUnit: '万吨',
            productionThisMonth: '76.72',
            lastMonth: '94.42',
            yearTotal: '330.51',
            ConteProduction: '166.38',
            YOY: "98.65"
        },
        {
            month: '2023-03',
            enterpriseName: '甘肃能化靖煤公司',
            productName: '原煤',
            productuUnit: '万吨',
            productionThisMonth: '83.03',
            lastMonth: '80.56',
            yearTotal: '238.56',
            ConteProduction: '219.69',
            YOY: "8.59"
        },
        {
            month: '2023-03',
            enterpriseName: '甘肃能化窑煤公司',
            productName: '原煤',
            productuUnit: '万吨',
            productionThisMonth: '94.42',
            lastMonth: '79.39',
            yearTotal: '253.67',
            ConteProduction: '221.66',
            YOY: "14.44"
        },
        {
            month: '2023-02',
            enterpriseName: '甘肃能化靖煤公司',
            productName: '原煤',
            productuUnit: '万吨',
            productionThisMonth: '80.56',
            lastMonth: '75',
            yearTotal: '155.56',
            ConteProduction: '146.48',
            YOY: "6.20"
        },
        {
            month: '2023-02',
            enterpriseName: '甘肃能化窑煤公司',
            productName: '原煤',
            productuUnit: '万吨',
            productionThisMonth: '79.39',
            lastMonth: '80',
            yearTotal: '220.37',
            ConteProduction: '98.29',
            YOY: "124.20"
        },
        {
            month: '2023-01',
            enterpriseName: '甘肃能化靖煤公司',
            productName: '原煤',
            productuUnit: '万吨',
            productionThisMonth: '75',
            lastMonth: '76.81',
            yearTotal: '75',
            ConteProduction: '72.39',
            YOY: "3.61"
        },
        {
            month: '2023-01',
            enterpriseName: '甘肃能化窑煤公司',
            productName: '原煤',
            productuUnit: '万吨',
            productionThisMonth: '80',
            lastMonth: '88.95',
            yearTotal: '80',
            ConteProduction: '54.37',
            YOY: "47.14"
        },
    ],
    data3: [{
        month: '2023-08',
        enterpriseName: '甘肃电投集团',
        productName: '发电量',
        productuUnit: '亿千瓦时',
        productionThisMonth: '',
        lastMonth: '',
        yearTotal: '220.34',
        ConteProduction: '209.21',
        YOY: "5.32"
    },],
    data4: [{
        month: '2023-08',
        enterpriseName: '兰石集团',
        productName: '石油钻采设备',
        productuUnit: '万吨',
        productionThisMonth: '',
        lastMonth: '',
        yearTotal: '1.89',
        ConteProduction: '1.27',
        YOY: "48.56"
    },
    {
        month: '2023-08',
        enterpriseName: '兰石集团',
        productName: '石油钻采设备',
        productuUnit: '万吨',
        productionThisMonth: '',
        lastMonth: '',
        yearTotal: '9.06',
        ConteProduction: '6.76',
        YOY: "34.04"
    },
    {
        month: '2023-08',
        enterpriseName: '甘肃电气集团',
        productName: '开关柜',
        productuUnit: '面',
        productionThisMonth: '',
        lastMonth: '',
        yearTotal: '6690',
        ConteProduction: '5815',
        YOY: "15.05"
    },
    {
        month: '2023-08',
        enterpriseName: '甘肃电气集团',
        productName: '电动机',
        productuUnit: '万千瓦',
        productionThisMonth: '',
        lastMonth: '',
        yearTotal: '104.3',
        ConteProduction: '93.39',
        YOY: "11.68"
    },

    {
        month: '2023-08',
        enterpriseName: '甘肃电气集团',
        productName: '交流发电机',
        productuUnit: '万千瓦',
        productionThisMonth: '',
        lastMonth: '',
        yearTotal: '32.11',
        ConteProduction: '22.38',
        YOY: "43.48"
    },
    {
        month: '2023-08',
        enterpriseName: '甘肃药业集团',
        productName: '元胡止痛滴丸',
        productuUnit: '亿粒',
        productionThisMonth: '',
        lastMonth: '',
        yearTotal: '21.93',
        ConteProduction: '16.91',
        YOY: "29.69"
    },
    {
        month: '2023-08',
        enterpriseName: '甘肃药业集团',
        productName: '宣肺止嗽合剂',
        productuUnit: '万盒',
        productionThisMonth: '',
        lastMonth: '',
        yearTotal: '2511.9',
        ConteProduction: '1042.71',
        YOY: "140.90"
    },

    {
        month: '2023-08',
        enterpriseName: '甘肃国投集团',
        productName: '精纺呢绒',
        productuUnit: '万米',
        productionThisMonth: '',
        lastMonth: '',
        yearTotal: '362.78',
        ConteProduction: '315.03',
        YOY: "15.16"
    },
    {
        month: '2023-08',
        enterpriseName: '甘肃国投集团',
        productName: '浓缩苹果汁',
        productuUnit: '万吨',
        productionThisMonth: '',
        lastMonth: '',
        yearTotal: '',
        YOY: ""
    },
    {
        month: '2023-08',
        enterpriseName: '甘肃国投集团',
        productName: '利乐包等产品',
        productuUnit: '万包',
        productionThisMonth: '',
        lastMonth: '4065',
        yearTotal: '2523',
        YOY: "61.12"
    },
    {
        month: '2023-08',
        enterpriseName: '甘肃科技集团',
        productName: '涂料',
        productuUnit: '万吨',
        productionThisMonth: '',
        lastMonth: '1.7',
        yearTotal: '1.48',
        YOY: "15"
    },
    {
        month: '2023-08',
        enterpriseName: '甘肃科技集团',
        productName: '化学助剂',
        productuUnit: '万吨',
        productionThisMonth: '',
        lastMonth: '0.78',
        yearTotal: '0.65',
        YOY: "20"
    },
    ]
}