const nationalCapital = [
    {
        department:'国资监管机构',
        money:'1040000',
        proportion:'11.39%',
    },
    {
        department:'政府部门',
        money:'0',
        proportion:'0.00%',
    },
    {
        department:'事业单位',
        money:'0',
        proportion:'0.00%',
    }
]
const stateOwnedLegalPersonCapital = [
    {
        department:'国有全资公司',
        money:'5000',
        proportion:'0.05%',
    },
    {
        department:'国有控股公司',
        money:'14351.67',
        proportion:'0.16%',
    },
    {
        department:'国有参股公司',
        money:'6809377.2556',
        proportion:'74.56%',
    },
    {
        department:'国有实际控制企业',
        money:'1233988.5128',
        proportion:'13.51%',
    }
]

const nonStateOwnedCapital = [
    {
        department:'社会团体',
        money:'11893.73',
        proportion:'0.13%',
    },
    {
        department:'自然人',
        money:'4289',
        proportion:'0.05%',
    },
    {
        department:'民营企业',
        money:'14428.72',
        proportion:'0.16%',
    },
    {
        department:'其他',
        money:'0',
        proportion:'0.00%',
    }
]
export {nationalCapital,stateOwnedLegalPersonCapital,nonStateOwnedCapital}
